### ISSUE TITLE
[Warlock] [Talent] Devastation not applying 5% crit chance to Destruction spells

### ISSUE THREAD

**Issue by Deadshade** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3674] opened 2015-07-28 11:04 UTC
Class: Warlock
Error Severity: Critical (no pun intended)
Spell ID's: 18130 (Devastation talent), 27209 (Shadow Bolt Tank 11)
Evidence: http://imageshack.com/a/img538/482/V9jv2B.jpg
Date/Time: 28.07.2015

Zone/Instance: Everywhere

What type of error occurred?:
The talent Devastation is not increasing the warlocks Spell Critical Strike Chance for destruction spells

What was the actual result vs. the expected result?: 
With 18.5% Spell Critical Strike Chance + Devastation Talent = 23% Critical Strike Chance. Screenshot shows that after over 200 Shadow Bolts the Critical strike chance is close to 18.5% as advertised in the Character pane and not close to 23% as it should be.

NB. Devastation increases Crit for Destruction spells, so it is not showing in the Character window. This is correct.

Can the error be repeated? If so, what are the steps?:
Create a warlock, learn Devastation (5 points) and spam Shadow Bolt (Rank 11) on a target dummy in Orgrimmar/Stormwind --> Observe your Spell Critical Strike Chance vs. what is shown in your Character pane, Actual Spell Critical Strike Chance should be 5% more than what the Character Window says.

Edit. Get an addon that captures damage done, like Recount and observe results.

**Comment by teddys** [comment] 2015-07-31 17:45
#3557
could be related

**Comment by Nick91** [comment] 2015-08-02 21:55
237 casts is hardly a reliable sample size.

**Comment by devidao** [comment] 2015-12-21 15:55
maybe 200 tries are not enough. I have looked it in the code and crit chance is successfully increased by 5 % with Devastation (Rank 5)

**Comment by Lederi** [comment] 2015-12-22 23:13
i just tested it with 750 shadow bolts and it was the expected value. Si i think it works fine.

**Comment by Nzzoth** [comment] 2015-12-23 11:43
Actually just to set the bar, 10000 is the reliable number we aim for when testing percentages.
Closed as it is working as intended.

**Closed by Nzzoth** 2015-12-23 11:43 UTC
Labels: Report.Incomplete
