### ISSUE TITLE
[Quest][Druid][Blade's Edge Mountains] The Book of the Raven.

### ISSUE THREAD

**Issue by pucko91** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3619] opened 2015-05-28 12:58 UTC
The Quest [The Book of the Raven] (https://www.wow-one.com/database/?quest=10980) is not working properly. The Item given [Seer's Stone] (https://www.wow-one.com/database/?item=32244) will not work with [Aether Ray Eye] (https://www.wow-one.com/database/index.php?item=32567). An error message shows that says "You need to be in Blade's Edge Mountains" even when being present in Blade's Edge Mountains at a number of different places in the zone but the same error message came up.

**Comment by Superhenk** [comment] 2015-06-02 11:50
Friend of mine had this problem too. It should obviously be fixed, but for the time being you can still complete it by actually being in "Blade's Edge Mountains". 
Go to the border of Blade's Edge and Zangarmarsh and the zone mentioned in the top right should be "Blade's Edge Mountains" , as opposed to for example "Vortex Pinnacle".

**Comment by pucko91** [comment] 2015-06-12 08:11
Well if that works it's good and all but the problem still remains and since that "sight" from what I have read it can dismount you and you drop to your death and you're back to square one again. It's still a problem but im glad it can be worked around.

**Comment by devastator** [comment] 2016-01-04 10:53
Could not reproduce the issue. Perhaps post screenshots to provide additional info on the circumstances

**Comment by Superhenk** [comment] 2016-01-04 11:28
This isn't something you can't reproduce after completing the quest,
obviously. Friend didn't take any screenshots, so you'll have to wait until
someone else posts those.

2016-01-04 11:53 GMT+01:00 devastator <notifications@github.com>:

**Comment by devastator** [comment] 2016-03-01 12:19
Closing, until more sufficient proof is found

**Closed by devastator** 2016-03-01 12:19 UTC
Labels: Class.Druid, Core.Quests, Report.Complete
