### ISSUE TITLE
MT HC - No loot on third boss

### ISSUE THREAD

**Issue by gymno123** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3679] opened 2015-08-03 00:08 UTC
Just did Magisters Terrace HC and the third boss didn't drop any BoJ or trinkets - unlootable. The door to last boss didn't open either.

I'm trying to get the tanking trinket from that boss. Will that be possible?

**Comment by Thetruecrow** [comment] 2015-08-03 09:58
Sorry about that, seems to be an error in our script, we're looking into it now to see what caused it.

Can you give me a bit more info? Were there any issues killing the other 4 adds that are spawned near the boss as well?

**Comment by gymno123** [comment] 2015-08-03 10:28
Well, the first time we attacked 2 of the mobs later despawned and the whole fight got reset. On the second try there were no problems, until we were to loot the boss

**Comment by gymno123** [comment] 2015-08-03 12:00
Do Feenix grant loot in these cases?

**Comment by gymno123** [comment] 2015-08-04 22:44
Would like to report that this happened again, when i did it yesterday it was fine. But today it bugged again.

**Comment by Raynez** [comment] 2015-08-09 15:58
From what i have seen and understood, this happens when you kill the Boss (Priest) itself first before the adds. Which should not be the case, shouldn't matter what order you kill them.

But from what i have seen, it bugs out if you kill boss 1st.

Hope this helped.

/Regards
Gruzzle/Golba

**Comment by devastator** [comment] 2016-02-15 14:17
Closing as the issue is supposed to be fixed. If the problem persists please comment to reopen

**Closed by devastator** 2016-02-15 14:17 UTC
