### ISSUE TITLE
Brutallus Burn and stomp.

### ISSUE THREAD

**Issue by pucko91** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3890] opened 2016-11-18 11:38 UTC
Archangel 2.4.3 Error Report Form

Report ID: How do I know, Titum001

Reporter Name: Titum

Date/Time: 161118 12:28ST

Error Severity:Game breaking

Zone/Instance: Sunwell Plateau

What type of error occurred?: Brutallus Stomp (spell=45185, wowhead info) Does not add debuff, Decreasing armor by 50%, and does not remove spell, Burn (spell=45141, wowhead info). Parallell Brutallus Burn (spell=45141, wowhead info) affects Hunter pets causing them to spread it further (even outside the raid)

What was the actual result vs. the expected result?: Actual result making Brutallus very much RNG, if tanks or pets gets the burn it's pretty much good night, if they don't it's not a problem. Exspected result is Stomp ability linked above removing burn on tanks and anyone in tank range (hunter pets).

Can the error be repeated? If so, what are the steps?: Yes, get burn on pets/tanks, get stomped and burn still remains.

Link to Video Evidence: Atm none exists additionally Hype guild is a competative guild and does not wish to share strategy like positioning openly in issue trackers, video can be linked to developers personally on demand (eventually).

External/Related Links:

Please detail your character’s race, class, and items (optional): To what end?

regards,

Titum
Elemental Overlord.

**Comment by ghost** [comment] 2016-11-18 18:52
@pucko91 No video necessary. Issue found, currently testing a solution. Thanks for the detailed report.

**Comment by Accorinrin** [comment] 2016-11-18 18:56
@pucko91 #hypecan'tstopme

**Comment by ghost** [comment] 2016-11-18 19:23
Just an update that Stomp removing Burn issue fix has been tested and confirmed. Working on pets part of it now.

**Comment by Zerixx** [comment] 2016-11-18 20:10
Looks like both things are taken care of now, @pucko91 

Hopefully permanently.

**Comment by ghost** [comment] 2016-11-19 18:09
Fixes tested and deployed to Live. Issue closed.

**Closed as completed by ghost** 2016-11-19 18:09 UTC
Labels: Report.Complete, Rep.FixConfirmed, Dev.OnLive
