### ISSUE TITLE
[Item] Hex Shrunken Head Cooldown-Share

### ISSUE THREAD

**Issue by Datbase** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3638] opened 2015-06-20 17:06 UTC
Report ID: 3638

Reporter Name: Frostboltlol

Date/Time: 20.06.15 19:00 CET

Zone/Instance: everywhere

What type of error occurred?: Cooldown is shared with wrong Items

What was the actual result vs. the expected result?:

Atm you cant use Hex Shrunken Head & Skull at the same time. In addition it's possible to use the Badge Trinket & Hex Shrunken Head at the same time. So atm its not possible to use this trinket with a use haste effect trinket at the same time.

Hex + haste Trinket = can't use together
Hex + Spell  Trinket = usable

normally it should be the other way around.

Hex + haste Trinket = usable
Hex + Spell  Trinket = can't use together

Can the error be repeated? If so, what are the steps?:

I think there is a wrong cooldown on Hex. I think his spellpower use generates a "haste use effect Cooldown"

**Comment by Hypnotizer** [comment] 2015-06-20 18:21
Duplicate of #3633 already denied.

**Closed** 2015-06-20 18:29 UTC
