### ISSUE TITLE
Quest: A Pawn of the Eternal Board No Cutscene Trigger

### ISSUE THREAD

**Issue by DeadlyMemory** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3706] opened 2015-09-21 22:53 UTC
When you interact with the crystalline tear outside of the Ahn'Qiraj gates a cutscene does not activate and the quest is unable to be completed.

http://wowwiki.wikia.com/wiki/Quest:A_Pawn_on_the_Eternal_Board
"Accepting the quest will trigger a cutscene with (until the Burning Crusade) unique background music:"

**Comment by roblockster** [comment] 2015-09-23 15:07
Thank you for taking the time to report, but it is a duplicate of #3402

**Closed by roblockster** 2015-09-23 15:07 UTC
