### ISSUE TITLE
[Mage] Master of Elements Talent and Aoe

### ISSUE THREAD

**Issue by ttanga** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3612] opened 2015-05-26 21:20 UTC
It seems Master of Elements talent has been changed in the last patch. There was mana refund from each crit of AoE before patch (i.e. you hit 5 mobs, and crit 2 of them, you will get 2x base mana back of your AoE spell like Flamestrike). Now it doesn't matter how many crits do you get, there is only one mana refund tick for each Flamestrike cast.

**Comment by Hypnotizer** [comment] 2015-05-27 06:05
Issue confirmed on PTR.

Create a Mage
.levelup 69
.gm off
.gm visible on
.l 29076 (Master of Elements)
.l 27086 (Flamestrike)
.m hp 1000000
.t test

Run into a bunch of mobs and review your combat log, and you'll see no matter how many crits you have you gain only from 1 crit as the poster say.

**Comment by Doppelmoral** [comment] 2015-05-28 07:49
Erm, working as intended. As reflected in the description it triggers per SPELL not amount of its critical hits ("one OR more"). Doesn't matter if you crit one mob or 10, you get 15/30% back flat as soon as any crit occured.

If Hypnotizer is a test team member I strongly suggest to properly research before validating incorrect reports.

**Comment by Doppelmoral** [comment] 2015-05-28 07:58
Erm, working as intended. As reflected in the description you get 15/30% flat returned as soon as the SPELL crits, not per actual, individual critical hits of the spell ("one OR more").

If Hypnotizer is part of the testing team I strongly suggest to do proper research (and apply common sense) before validating incorrect reports.

**Comment by Nzzoth** [comment] 2015-05-28 08:55
Greetings,

Would you be so kind to provide source of that information Doppelmoral?

Kind regards.

**Comment by Involve** [comment] 2015-05-28 10:51
http://www.wowhead.com/forums&topic=19487/imp-flamestrike-am-i-crazy

**Comment by ttanga** [comment] 2015-05-28 13:01
1. Multi mana back mechanic from Flamestrike crits was working a patch ago on AA (got fixed intentionally?)
2. Too much time has passed since i did Flamestrike aoe on Hyjal trash on retail, but as far as i remember there was multiple MoE procs (not 100% sure tho), the topic starter from your wowhead link pretty much summed my feelings about it. Improved FS was very powerful aoe on that trash coz of mana refunds.
3. How that link could be a prove. The last guy on that topic just said 'no it's not working'. Proves?

That issue need more research

**Comment by Doppelmoral** [comment] 2015-05-28 13:02
^ plus the quite transparent tooltip plus the illogical assumption that a DpS could (should) grant more mana than it consumes makes it save to say it's not a valid report.

(There's more evidence on the internet which claim it only triggers once via AoE, none of them are alone conclusive enough to shoot this report down at once - hoping for knowledgeable mages to show up)

**Comment by Asuschrist** [comment] 2015-05-28 15:28
Google a bit and you'll realize that it's working as intended now.
It's supposed to return 30% mana of the casted spell, no matter how many crits it does to several targets.

**Comment by Stoniz** [comment] 2015-05-28 18:20
Hello Nzzoth
Pointing out to Doppelmora and i would like to confirm what he said it's working as intended now
http://wowwiki.wikia.com/Master_of_Elements

*Master of Elements* is a popular PvE talent for any talent build while spending points in the Fire tree. It restores up to 15/30% of the mana cost of any spell that critically hits one or more targets (so AoE spells such as Flamestrike, Cone of Cold and Blast Wave are affected by this talent). Since most mages critically hit between 20 and 40% of the time this talent is equivalent to an effective mana cost reduction of all spells which can critically strike.

As mentioned above Master of elements function as mana reduction cost and would never be used as source to replenish mana/get more than you spend.

**Comment by Nzzoth** [comment] 2015-05-28 19:17
Issue closed as it is working as intended.

**Closed by Nzzoth** 2015-05-28 19:17 UTC
