### ISSUE TITLE
[MAJOR][Rogue] Cheap shot bug

### ISSUE THREAD

**Issue by takza** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3520] opened 2015-01-12 05:30 UTC
If you try to cheap shot someone, and the person is moving or you turn around quickly as you press the button, you leave stealth with nothing happening.

This is one of the MAJOR gamebreaking PvP bugs for rogues.

**Comment by Nzzoth** [comment] 2015-01-12 11:25
Hello Takza, I was unable to reproduce this on Warsong. If the person is moving it simply says "Target out of range" (this is already a known issue) and if you turn around quickly it says "Interupted". In both cases you do not break out of stealth and dont preform an action. Can you please provide us with some evidence for this issue and can you include the realm.

**Comment by takza** [comment] 2015-01-12 11:44
It is posted on the Archangel 2.4.3 bugtracker..

**Comment by Nzzoth** [comment] 2015-01-12 13:24
Whoops my bad.

**Comment by Forcy** [comment] 2015-02-02 21:13
Combatlog of (chasing) attacker:
![ss-issue](https://f.cloud.github.com/assets/2018747/241406/1e8ad766-89ab-11e2-9a2e-c1302613ae08.jpg)
Combatlog of (fleeing) victim:
![ss-issue-victim](https://f.cloud.github.com/assets/2018747/241410/300ad306-89ab-11e2-8951-b27af95088f1.jpg)

I tested the problem with warrior, rogue and shaman, but only was able to reproduce it repeatedly with the shamans Stormstrike ability. In the combat logs you can see the "out of range" message, after that Stormstrike is "successfully" used, applies the debuff on the enemy BUT does no damage whatsoever but is on cooldown ("Not yet recovered"). I had also cases where the ability was just on cooldown without applying debuff nor doing damage. (Tests done with ~55-60 ms latency)

How to reproduce:
You need 2 clients, on one create a tauren shaman
.levelup 69
.learn 17364 (Stormstrike)
.add 28545 (Edgewalker Longboots)
.add 35399 (Minor Runspeed enchant for boots)
.t test
 On the other one create a draenei priest
.levelup 69
.mod hp 1000000
.t test

Bind Stormstrike to any button on your keyboard, equip the boots and apply the minor runspeed enchant to them.
On the priest you start auto-running by pressing Numlock on your keyboard, follow with the shaman.

For me it was helpful to use an tight angle while chasing like in the picture below
![repro](https://f.cloud.github.com/assets/2018747/241429/7381f32e-89ad-11e2-9dac-3b6e37cf180b.jpg)

If you continuously spam now the ability and keep running like that there will at some point the ability go off (being on cooldown) but not working properly, like in most cases just doing nothing at all.
I am posting this here because I suspect the same problem with rogues and their (in rare occasions) not working
openers. It occurs to me, that a combination of delay, maximum range of an ability and minor difference in runspeed causes this. Anyway, I hope this repro-guide and combat logs help to pin down the problem.

**Comment by Forcy** [comment] 2015-02-02 21:13
https://www.youtube.com/watch?v=Gp7Y5QzYQtQ&feature=youtu.be

**Comment by takza** [comment] 2015-02-02 21:29
I'm no good with the commands, but you can try with cheap shot.

Stand still on one target, and on rogue, turn quickly while you try to apply cheapshot. Just keep trying a few times, that should bug it.

**Comment by warlee** [comment] 2015-03-26 02:39
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3201

**Comment by Forcy** [comment] 2015-04-06 16:44
Fixed with 13.1

**Closed by Forcy** 2015-04-06 16:44 UTC
Labels: Class.Druid, Class.Rogue, Report.Complete
