### ISSUE TITLE
Wind stones

### ISSUE THREAD

**Issue by kildrazien** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3676] opened 2015-07-31 05:28 UTC
Wind stones in silithus are unresponsive to anything that you do, and will only reply to interaction with "Greetings, (Name)". They should either burn the person who clicks them (if they have no twilight trappings set) or summon a templar/duke/Lord.

**Comment by Hypnotizer** [comment] 2015-07-31 11:13
Duplicate of #1469 #1192 #3631 closed.

**Closed** 2015-08-02 22:30 UTC
