### ISSUE TITLE
[Priest] [Spell] Mind vision interrupts on target's movement

### ISSUE THREAD

**Issue by orgasmix** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3837] opened 2016-08-04 12:19 UTC
(shamelessly copied gAdrev's issue that was about Warsong... because it has been present on Archangel too, and since I started playing)

Spell ID 10909
http://db.vanillagaming.org/?spell=10909

When cast on a target, channeling is stopped as soon as the target moves (it should stay on until the caster cancels it or the channeling expires).

**Comment by lajhar** [comment] 2016-08-04 22:02
Duplicate of #3737

**Closed by lajhar** 2016-08-04 22:02 UTC
