### ISSUE TITLE
Seal of Command and Seal of Blood receive full holy damage bonus from Judgement of the Crusader

### ISSUE THREAD

**Issue by mondegoftw** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3688] opened 2015-08-17 14:48 UTC
It's good time this gets looked at - makes horde retribution paladins entirely broken.

Seal of Blood procs from Crusader Strike (should not happen). 

Seal of Blood procs Windfury Totem (should not happen).

This makes horde ret paladins ~completely~ broken. They are by far the most broken spec here. The fix is simple.

**Comment by mondegoftw** [comment] 2015-08-17 14:50
Refer to this comment/thread for Crusader Strike SoB procs: https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3482#issuecomment-107695595

**Comment by roblockster** [comment] 2015-08-17 16:29
This is a duplicate of #3482 . SOB is supposed to proc off of Windfury attacks. 

"seal of blood procs off of all attacks, meaning your windfurry proc will also proc seal of blood making it even better."
http://forums.elitistjerks.com/topic/17058-retribution-dps-theorycraft/?p=549114

**Comment by mondegoftw** [comment] 2015-08-21 17:37
I'm not sure what causes it, and don't have access to anything that'd let me test it at the moment, but the damage of SoB is way off. SoC seems about right, and SoB should do about 10% more dmg than SoC. So since SoC is ~25% total damage in a normal ret pal rotation, SoB should be ~27.5%. 

It's closer to 50.

I don't know exactly what's causing the bug, but I'm pointing you in the direction of a really huge bug. Things like these can't be ignored on a server that's meant to be blizzlike.

**Comment by Nick91** [comment] 2015-08-21 18:10
The bug lies with Windfury Totem itself and not with SoB.

https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2865#issuecomment-19391194

> As suspected this has been changed with a hotfix applied 2007/8/10 (http://blue.mmo-champion.com/topic/18088-10-08-windfury-totem-hotfix/).
> 
> __Current situation:__
> 
> The Windfury effect (http://database.wow-one.com/index.php?spell=25582) gained by the Windfury Totem (http://database.wow-one.com/index.php?npc=15497) does procc of any attack, such as Sunder Armor, Harm String, Rend and similar.
> 
> __Desired situation:__
> 
> The Windfury effect (spell=25582) should solely procc off white damage abilities (Auto-attack, sword spec-procc) and abilities which turn your next White damage attack into a Melee special attack (so-called On-next-hit-abilities such as Cleave spell=25231 and Heroic Strike spell=29707).

The comment is from an issue that is closed but not fixed.

Examples:

__Current:__
* Autoswing + Seal of Blood (2 proc chances for WF, 36%)
* Crusader Strike + Seal of Blood (2 proc chances for WF)
* Autoswing + Seal of Blood + Windfury + Seal of Blood (4 proc chances for WF, 59%)

__Desired:__ (assuming WF is meant to be capable of proccing WF again, and a WF attack procs Seal of Blood)
* Autoswing + Seal of Blood (1 proc chance for WF, 20%)
* Crusader Strike (0 proc chances for WF)
* Autoswing + Seal of Blood + Windfury + Seal of Blood (2 proc chances for WF, 36%)

**Comment by mondegoftw** [comment] 2015-08-22 14:21
That probably explains some of it; but I'm sure it's not all of it because it still doesn't explain how SoB does more damage than white hits. That can't be caused solely by WF proccing too much, since if anything that'd increase white hits and sob damage proportionally, keeping SoB at roughly half as much dmg as white.

**Comment by mondegoftw** [comment] 2015-08-23 21:40
https://www.youtube.com/watch?v=KCdcrclg8B4 proof ret pala dps isn't blizzlike - i'm sure if you look into the numbers it's caused by SoB. His SoB does roughly 400 DPS, and his total dps is around/below 2k. Means SoB accounts for 20% of his damage. And on feenix, SoB is at least 40% of damage.

Only WF totem bug would NOT make SoB do twice as much damage relative other spells. There's a bug with SoB (beyond WF and CS bugs). Probably it's in the damage calculations. Incidentally, SoR damage calcs are off too.

**Comment by kildrazien** [comment] 2015-08-24 17:06
It's worth noting the post date of the video is in 2012, and the forum post that is linked in the description was posted in 2013. This leads to the conclusion that it is not necessarily blizzlike, as it could be on a private server.

**Comment by Nick91** [comment] 2015-08-25 11:27
Yes, the video posted in the comment above(https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3688#issuecomment-133941835) is from a private server.

---

@roblockster Please re-evaluate the labels for this issue, now that a bug has been identified with the spell itself; description and reproduction guide see below.

---

I don't have access to the PTR to do more sophisticated tests, however I looked into your concern regarding that the damage SoB does is too high, logged my Horde Paladin and swung a taget dummy. I came to the conclusion, that, circumstantially, Seal of Blood is doing more than the intended damage.

http://forums.elitistjerks.com/topic/9664-paladin-seal-mechanics/

> I'm not sure if this is what you're actually asking - what spell damage coefficient does Seal of Blood get? The answer is zero. Seal of Blood receives absolutely no bonus whatsoever from +damage.

http://web.archive.org/web/20080221133542/http://forums.worldofwarcraft.com/thread.html?topicId=104544938&sid=1&pageNo=6

> 3. How come JotC (additional holy damage) doesn't really give a damage boost to seal of blood? 

> 3) Seal of Blood itself has no spell damage coefficient

Considering these two sources, there is a partial bug with the damage dealt by Seal of Blood. Spell damage from gear does not influence the damage dealt by the Seal, but the complete bonus from a Judgement of the Crusader is applied to each melee swing. With Rank 7 that is 219, if applied with Libram of Zeal +47, it's 266.

## Current bugs related to Seal of Blood

### [1/3] The Seal damage scales 100% with the holy spell damage bonus of Judgement of the Crusader

__Desired:__ The _Seal_ damage is not supposed to be affected by Judgement of the Crusader at all. [[1]](http://forums.elitistjerks.com/topic/9664-paladin-seal-mechanics/) [[2]](http://web.archive.org/web/20080221133542/http://forums.worldofwarcraft.com/thread.html?topicId=104544938&sid=1&pageNo=6) Reproduction guide see below.

Note that the damage of _Judgement of Blood_, the spell triggered if you use _Judgement_ while being self-buffed with _Seal of Blood_, is supposed to be affected by Judgement of the Crusader by (1.5/3.5)%.

#### Reproduction guide

You will require one client in order to reproduce this issue

Create a Paladin
.levelup 69
.gm off
.gm visible on
.learn 202 (Two-handed Swords)
.add 35015
.t orgr
.go c dummy
.learn 27158 (Seal of the Crusader)
.learn 31892 (Seal of Blood)
.learn 20271 (Judgement)
.max

* Equip the sword and cast Seal of Blood. Target a Dummy next to you autoattack it. Observe the damage.
* Now suspend attacking, cast Seal of the Crusader, cast Judgement and then cast Seal of Blood. Start autoattacking the target. Observe the damage (219 more damage is dealth than in the previous step).

### [2/3] Crusader Strike is triggering damage dealing Seals (such as Seal of Blood)

__Desired:__ Crusader Strike is _not supposed_ to trigger damage dealing Seals, see Issue #3482 (With reproduction guide but unlabelled!)

### [3/3] The Windfury Totem Effect is triggered by yellow attacks (such as Seal of Blood)

__Desired:__ The Windfury Totem Effect is supposed to be triggered only by white attacks, see Issue #2865 (Closed but not fixed; not on live!)

**Comment by mondegoftw** [comment] 2015-08-25 11:40
Thanks a bunch, Nick91. I was convinced there was a 3rd bug relating to the actual SoB proc number, but wasn't able to find the exact source without access to PTR or a horde paladin.

Well done. Can't wait for this to be fixed.

**Comment by roblockster** [comment] 2015-08-28 16:28
The holy damage bonus from Judgement of the Crusader is currently separate from the spellpower bonus it provides to holy spellpower-based spells, and is applying an extra source of holy damage to Seal of Blood and Seal of Command (27170).

**Comment by endemol88** [comment] 2015-09-03 20:18
The seal only scales with weapon damage, not spell damage. It therefore heavily favors melee-geared Paladins (mostly Retribution Paladins), rather than spelldamage-geared Paladins. Note that the Judgement does scale with spell damage. Source ===> http://wowwiki.wikia.com/wiki/Seal_of_Blood

**Comment by Cerebov** [comment] 2015-09-03 23:50
reply to nick91's 1),2),3)s.

first of all, 
4) i would like to remind about this issue https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3483
  this bug affects SoB and SoC and is actually decreasing their damage.
2). https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3482 
    this was reported earlier. I dont have anything to add, exept i would like to clarify that Crusader strike activates Seal of Blood and Seal of Righteosness atm(live), it doesnt affect Seal of Command and Seal of Vengeance. pls dont fix what is not broken. (in this way anyways, see https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3240 )
3) My testing today showed that Windfury attack doesnt proc off Seal of Blood. ( and Seal of Command)
    You can actually test it yourself.
    Get a pally and a shaman. Put wf and healing stream(to negate SoB backlash). Dont forget to renew totems every 2 mins.
     Hit a dummy for 100 hits. U would see in recount ~120 autoattacks.
    Now do it with SoB up(dont forget to renew it every 30sec). You would see in the end ~120 autoattacks and ~120 SoBs in your recount. 
     Dont forget to renew SoB and totems.( i switched to my shaman and renewed totems every 25 swings).
   Do it couple of times and round the results.
    If that assumption is true, you would see ~140 autoswings with SoB up, because having doble chance of proc doubles the results. But you would get ~120 autoswings even with SoB up.
  Also, if WF does in fact proc off SoB swing, you would also see things like Crusader strike->SoB swing->WF swing (off SoB)->SoB (off WF swing). IF you cast Crusader strike inbetween autoattacks, that would happen sometimes and there would be no autoattacks that mislead you.
But in 2 years raiding as ret pally ive never seen it happening.
Same thing goes for SoC. with the bugged belay atm its easy to notice that standalone SoC swing and Crusader strike+SoB swing never proc WF swings.

**Comment by Cerebov** [comment] 2015-09-03 23:58
Now for 1). 
This is the hardest part actually.

**Comment by repae1f** [comment] 2016-06-02 08:55
Seal of Blood spell coefficient  0.0
http://web.archive.org/web/20081218133415/http://elitistjerks.com/f47/t19038-spell_coefficients/

**Comment by Kaiitothewai** [comment] 2016-07-14 16:06
Hope to see Deviado look into this soon

**Comment by lajhar** [comment] 2016-11-23 23:54
Fix confirmed on PTR.
SoB damage does not proc off Windfury attack (nor does Crusader strike, or any yellow attack). Seal of Blood damage does not scale with Judgement of the Crusader anymore. Crusader Strike does not activate damage seals (such as Seal of Blood)

**Comment by lajhar** [comment] 2016-11-26 14:34
Already on live (15.6)

**Closed by lajhar** 2016-11-26 14:34 UTC
Labels: Class.Paladin, Core.Spells, Dev.OnLive, Rep.FixConfirmed, Report.Complete
