### ISSUE TITLE
Immobilize

### ISSUE THREAD

**Issue by asdsha** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3696] opened 2015-08-31 00:36 UTC
Currently, there is no such thing on the server as immobilize, all the immobilizes belong to ROOTS category which is a gamebreaker when it comes to PvP.

Immobilizes are: Improved Wing Clip, Improved Hamstring, Feral Charge, Chastise (these are the ones that are in players' disposal) and more.
Unlike roots, immobilizes SHOULD NOT get broken on damage no matter how much damage an immobilized target has received, they also belong to a different DR group but i'll open another issue on that.

**Comment by devastator** [comment] 2016-01-04 12:41
Please provide proofs

**Comment by teddys** [comment] 2016-11-30 14:44
https://youtu.be/-41Dgo6auCA?t=59 900 hit + chain lightning, doesn't break
https://youtu.be/-41Dgo6auCA?t=481 1400 crit + some bleed ticks, doesn't break
https://youtu.be/-41Dgo6auCA?t=663 takes some hits, doesn't break
https://youtu.be/-41Dgo6auCA?t=932 full dots + melee, doesn't break

feral charge is the same effect (immobilize)
https://youtu.be/IR1DMSfGrN8?t=240 doesn't break from taking 20%+ dmg
https://youtu.be/IR1DMSfGrN8?t=266  doesn't break
https://youtu.be/IR1DMSfGrN8?t=328 doesn't break untill he shifts to bear

imp wing clip, same effect
https://youtu.be/VhCI3DDvGGU?t=839 autoshot + multishot, doesn't break
https://youtu.be/VhCI3DDvGGU?t=857 more than 35% of priest's hp pool .. doesn't break

that enough?

**Comment by lajhar** [comment] 2016-12-01 18:27
Tested, and sometimes it breaks on damage, sometimes it doesn't, works as intended.

>  Immobilize effects do not break automatically break on damage, but attacking an immobilized target does give them a heightened chance to cause them to break free.

[Source](http://wow.allakhazam.com/wiki/immobilize_(wow))

Closing until adverse opinions.

**Closed by lajhar** 2016-12-01 18:27 UTC
Labels: Report.Denied, Report.Incomplete

**Comment by teddys** [comment] 2016-12-02 17:53
Doesn't say anything about feral charge and improved wing clip.
And imp hamstring literally breaks every single time.
