### ISSUE TITLE
Quest The Foot of the Citadel bugged

### ISSUE THREAD

**Issue by NormantasKudzma** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3840] opened 2016-08-05 19:44 UTC
What : Quest [The Foot of the Citadel](http://wow-one.com/database/?quest=10876)

Links : [Challenge from the horde](http://wow-one.com/database/?item=31702) , [Force-Commander Gorax](http://wow-one.com/database/index.php?npc=19264) , [Hand of Kargath](http://wow-one.com/database/?npc=22374) , [Gorax's Corpse](http://wow-one.com/database/index.php?object=185223)

How it works: you cannot use the `Challenge from the horde` banner on Gorax's corpse after killing Force-Commander Gorax.

How it should work: you should be able to use the item on Gorax's corpse to summon Hand of Kargath.

Screenshot : [me, trying to use banner on the corpse](http://prnt.sc/c23ig4)

**Comment by lajhar** [comment] 2016-08-05 22:58
Duplicate of #3807

**Closed by lajhar** 2016-08-05 22:58 UTC
