### ISSUE TITLE
Seal of Righteousness damage

### ISSUE THREAD

**Issue by teddys** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3634] opened 2015-06-10 12:25 UTC
http://wowwiki.wikia.com/Seal_of_Righteousness?oldid=1329860

current situation : 1,8 weapon 440ap 600 spell dmg = ~350 dmg
expected : less than 350

https://www.youtube.com/watch?v=kNqOHEa1_Ng
shockadin means he has full spell damage gear (around 1100 spell damage) and he does 340 damage with righteousness AFTER judging crusader. Here you do 350 WITHOUT judging crusader WITH 600 spell damage.

**Comment by roblockster** [comment] 2015-06-10 14:54
Duplicate of #2482

**Closed** 2015-06-10 19:18 UTC
