### ISSUE TITLE
stunned with divine shield

### ISSUE THREAD

**Issue by soda09** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3859] opened 2016-09-16 12:59 UTC
one can be stunned, when using divine shield. But it should make immune to any spell.

**Comment by lajhar** [comment] 2016-09-16 16:21
Couldn't reproduce it. I tried with several type of stun effects, but the paladin was immune to all of them. Can you give me additional details, what kind of item/spell/NPC ability stunned you while you were using Divine Shield?

**Comment by soda09** [comment] 2016-09-17 08:43
I was stunned by an meele NPC at the tower on the road up to hearthglen.

**Comment by lajhar** [comment] 2016-12-14 22:16
Tested the NPC ability, works as intended (Divine shielded targets were immune).
Closing until evidence's provided

**Closed by lajhar** 2016-12-14 22:16 UTC
Labels: Report.Incomplete
