### ISSUE TITLE
[Item Set] Shaman Tier 6- Skyshatter Raiment

### ISSUE THREAD

**Issue by Xerel** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3554] opened 2015-03-16 15:50 UTC
http://www.wow-one.com/database/index.php?itemset=683

    2 pieces: Your Chain Heal ability costs 10% less mana.
    4 pieces: Increases the amount healed by your Chain Heal ability by 5%.

Current State- Chain heal is not receiving the benefit of 4 pieces as stated above.

**Comment by Nzzoth** [comment] 2015-11-30 20:49
Tested on PTR and the set bonus worked just fine, closing unless someone provides me with evidence that this indeed isn't working as intended.

**Closed by Nzzoth** 2015-11-30 20:49 UTC
Labels: Class.Shaman, Core.Items, Report.Complete
