### ISSUE TITLE
[Item] Unable to use Hex Shrunken Head with Skull of Guldan

### ISSUE THREAD

**Issue by warlee** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3633] opened 2015-06-09 17:44 UTC
Current situation: Using Hex Shrunken Head or The Skull of Gul'dan puts each other on 20 seconds cooldown. 

Desired situation: You should be able to use both items same time (just as Icon of the Silver Crescent and The Skull of Gul'dan). It should only put on CD other trinkets with '+spell damage/healing on use'.

Item ID 
The Skull of Gul'dan: 32483
Hex Shrunken Head: 33829
Icon of the Silver Crescent: 29370

Wowwiki:
jourikdv on 2007/11/27 (Patch 2.3.0)
This has been fixed in 2.3.2. It now works like other damage trinkets in that using it activates a cooldown on the other damage trinket.

**Comment by faustrech** [comment] 2015-06-10 04:04
No offense, but thats complete bs. You CAN'T use both items same time and that's a sure thing. Don't watch wowwikki for such things, wowhead has the option http://www.wowhead.com/item=32483/the-skull-of-guldan#dropped-by "shared cooldown". Hex is in there, just like every dmg trinket :D

**Comment by Dorakrab** [comment] 2015-06-11 01:39
i dont understand you, what you linked from wowwiki says that these trinkets should not be usable together, so why are u saying that they should be? 

"using it activates a cooldown on the other damage trinket." - your post.

**Comment by Dorakrab** [comment] 2015-06-11 01:42
check the "shared cooldown" section on wowhead, it has Skull of GUl'dan there and also commets from patches 2.4.2 say that these trinkets cant be used at the same time

**Comment by Nzzoth** [comment] 2015-06-11 13:55
Hello Dorakrab,

What he is refering to is that item 33829 doesn't share cooldown or puts item 32483 on cooldown as one is a damage trinket the other one is a "haste" trinket. From what you have linked I found no evidence in comments proving this claim to be wrong and the shared cooldown tab you linked includes current retail patch therefor it will not be taken into account.

**Comment by repae1f** [comment] 2015-06-11 18:02
Any trinket use start 30 sec cooldowns on ALL trinkets. I played in actual time on official server

**Comment by warlee** [comment] 2015-06-11 18:43
^30 seconds? Must have been different offical server or different actual time.
Nethertheless report incomplete until provided sufficient video proof

**Comment by Stoniz** [comment] 2015-06-11 22:40
Hello,i did some researches and i tested few of stuffs so far i was able to confirm :
** First : When using skull of gul'dan first it  does not put icon of the silver crescent on 20 sec cool-down, not sure if this Works as intended since i found a lot of debate.

3/4 Says that using Skull first will not put any other trinket on cool-down.
1/4 Says that Skull doesn't share any cool-down.
http://wowwiki.wikia.com/Talk:The_Skull_of_Gul%27dan#Use  
http://www.wowhead.com/item=32483/the-skull-of-guldan#comments:id=159977
http://www.wowhead.com/item=32483/the-skull-of-guldan#comments:id=113166
http://wowmb.net/forums/206241-post8.html

I'll do more researches in order to confirm this.

**Comment by repae1f** [comment] 2015-06-13 06:12
http://www.youtube.com/watch?v=o3kAugC9iec  video proof 0:09

**Comment by Nzzoth** [comment] 2015-06-13 08:58
Thank you, issue denied and closed as it's working as intended.

**Closed by Nzzoth** 2015-06-13 08:58 UTC
Labels: Core.Items, Database.Items, Report.Incomplete
