### ISSUE TITLE
Akil`Zon (Zul Aman)

### ISSUE THREAD

**Issue by ovpavel** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3651] opened 2015-07-01 17:01 UTC
During an electrical storm cast Static Disguption and the raid dies.

Bosses do not kill, all raids now it is passed.

**Comment by ovpavel** [comment] 2015-07-01 17:01
http://wowwiki.wikia.com/Akil'zon_(original)

**Comment by Hypnotizer** [comment] 2015-07-01 19:34
Duplicate of #3621 closed.

**Closed** 2015-07-01 20:40 UTC
